/*
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`crm_tasks_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CrmTasksGetError {
    Status400(models::ErrorModel),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`crm_tasks_id_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CrmTasksIdDeleteError {
    Status400(models::ErrorModel),
    Status404(models::ErrorModel),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`crm_tasks_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CrmTasksIdGetError {
    Status400(models::ErrorModel),
    Status404(models::ErrorModel),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`crm_tasks_id_patch`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CrmTasksIdPatchError {
    Status400(models::ErrorModel),
    Status404(models::ErrorModel),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`crm_tasks_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CrmTasksPostError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`crm_tasktypes_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CrmTasktypesGetError {
    UnknownValue(serde_json::Value),
}

pub async fn crm_tasks_get(
    configuration: &configuration::Configuration,
    filter_left_square_bracket_type_right_square_bracket: Option<&str>,
    filter_left_square_bracket_status_right_square_bracket: Option<&str>,
    filter_left_square_bracket_date_right_square_bracket: Option<&str>,
    filter_left_square_bracket_assign_to_right_square_bracket: Option<&str>,
    filter_left_square_bracket_contacts_right_square_bracket: Option<&str>,
    filter_left_square_bracket_deals_right_square_bracket: Option<&str>,
    filter_left_square_bracket_companies_right_square_bracket: Option<&str>,
    date_from: Option<i32>,
    date_to: Option<i32>,
    offset: Option<i64>,
    limit: Option<i64>,
    sort: Option<&str>,
    sort_by: Option<&str>,
) -> Result<models::TaskList, Error<CrmTasksGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_filter_left_square_bracket_type_right_square_bracket =
        filter_left_square_bracket_type_right_square_bracket;
    let p_filter_left_square_bracket_status_right_square_bracket =
        filter_left_square_bracket_status_right_square_bracket;
    let p_filter_left_square_bracket_date_right_square_bracket =
        filter_left_square_bracket_date_right_square_bracket;
    let p_filter_left_square_bracket_assign_to_right_square_bracket =
        filter_left_square_bracket_assign_to_right_square_bracket;
    let p_filter_left_square_bracket_contacts_right_square_bracket =
        filter_left_square_bracket_contacts_right_square_bracket;
    let p_filter_left_square_bracket_deals_right_square_bracket =
        filter_left_square_bracket_deals_right_square_bracket;
    let p_filter_left_square_bracket_companies_right_square_bracket =
        filter_left_square_bracket_companies_right_square_bracket;
    let p_date_from = date_from;
    let p_date_to = date_to;
    let p_offset = offset;
    let p_limit = limit;
    let p_sort = sort;
    let p_sort_by = sort_by;

    let uri_str = format!("{}/crm/tasks", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_filter_left_square_bracket_type_right_square_bracket {
        req_builder = req_builder.query(&[("filter[type]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_filter_left_square_bracket_status_right_square_bracket {
        req_builder = req_builder.query(&[("filter[status]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_filter_left_square_bracket_date_right_square_bracket {
        req_builder = req_builder.query(&[("filter[date]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_filter_left_square_bracket_assign_to_right_square_bracket {
        req_builder = req_builder.query(&[("filter[assignTo]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_filter_left_square_bracket_contacts_right_square_bracket {
        req_builder = req_builder.query(&[("filter[contacts]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_filter_left_square_bracket_deals_right_square_bracket {
        req_builder = req_builder.query(&[("filter[deals]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_filter_left_square_bracket_companies_right_square_bracket {
        req_builder = req_builder.query(&[("filter[companies]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_date_from {
        req_builder = req_builder.query(&[("dateFrom", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_date_to {
        req_builder = req_builder.query(&[("dateTo", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_sort {
        req_builder = req_builder.query(&[("sort", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_sort_by {
        req_builder = req_builder.query(&[("sortBy", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("api-key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TaskList`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TaskList`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CrmTasksGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn crm_tasks_id_delete(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<(), Error<CrmTasksIdDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;

    let uri_str = format!(
        "{}/crm/tasks/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("api-key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<CrmTasksIdDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn crm_tasks_id_get(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<models::Task, Error<CrmTasksIdGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;

    let uri_str = format!(
        "{}/crm/tasks/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("api-key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Task`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Task`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CrmTasksIdGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn crm_tasks_id_patch(
    configuration: &configuration::Configuration,
    id: &str,
    crm_tasks_id_patch_request: models::CrmTasksIdPatchRequest,
) -> Result<(), Error<CrmTasksIdPatchError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_crm_tasks_id_patch_request = crm_tasks_id_patch_request;

    let uri_str = format!(
        "{}/crm/tasks/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("api-key", value);
    };
    req_builder = req_builder.json(&p_crm_tasks_id_patch_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<CrmTasksIdPatchError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn crm_tasks_post(
    configuration: &configuration::Configuration,
    crm_tasks_post_request: models::CrmTasksPostRequest,
) -> Result<models::CrmTasksPost201Response, Error<CrmTasksPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_crm_tasks_post_request = crm_tasks_post_request;

    let uri_str = format!("{}/crm/tasks", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("api-key", value);
    };
    req_builder = req_builder.json(&p_crm_tasks_post_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CrmTasksPost201Response`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CrmTasksPost201Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CrmTasksPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn crm_tasktypes_get(
    configuration: &configuration::Configuration,
) -> Result<models::TaskTypes, Error<CrmTasktypesGetError>> {
    let uri_str = format!("{}/crm/tasktypes", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("api-key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TaskTypes`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TaskTypes`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CrmTasktypesGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
