/*
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EcommerceAttributionMetricsGet200ResponseTotals : Attribution list aggregated totals
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EcommerceAttributionMetricsGet200ResponseTotals {
    #[serde(rename = "ordersCount")]
    pub orders_count: f64,
    #[serde(rename = "revenue")]
    pub revenue: f32,
    #[serde(rename = "averageBasket")]
    pub average_basket: f32,
}

impl EcommerceAttributionMetricsGet200ResponseTotals {
    /// Attribution list aggregated totals
    pub fn new(
        orders_count: f64,
        revenue: f32,
        average_basket: f32,
    ) -> EcommerceAttributionMetricsGet200ResponseTotals {
        EcommerceAttributionMetricsGet200ResponseTotals {
            orders_count,
            revenue,
            average_basket,
        }
    }
}
