/*
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContactErrorModel {
    /// Error code displayed in case of a failure
    #[serde(rename = "code")]
    pub code: Code,
    /// Readable message associated to the failure
    #[serde(rename = "message")]
    pub message: String,
    /// Additional information about the error
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

impl ContactErrorModel {
    pub fn new(code: Code, message: String) -> ContactErrorModel {
        ContactErrorModel {
            code,
            message,
            metadata: None,
        }
    }
}
/// Error code displayed in case of a failure
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "invalid_parameter")]
    InvalidParameter,
    #[serde(rename = "missing_parameter")]
    MissingParameter,
    #[serde(rename = "document_not_found")]
    DocumentNotFound,
    #[serde(rename = "account_in_process")]
    AccountInProcess,
    #[serde(rename = "duplicate_parameter")]
    DuplicateParameter,
    #[serde(rename = "method_not_allowed")]
    MethodNotAllowed,
    #[serde(rename = "out_of_range")]
    OutOfRange,
}

impl Default for Code {
    fn default() -> Code {
        Self::InvalidParameter
    }
}
