/*
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDomainModelDnsRecords {
    #[serde(rename = "dkim_record", skip_serializing_if = "Option::is_none")]
    pub dkim_record: Option<Box<models::CreateDomainModelDnsRecordsDkimRecord>>,
    #[serde(rename = "brevo_code", skip_serializing_if = "Option::is_none")]
    pub brevo_code: Option<Box<models::CreateDomainModelDnsRecordsDkimRecord>>,
    #[serde(rename = "dmarc_record", skip_serializing_if = "Option::is_none")]
    pub dmarc_record: Option<Box<models::CreateDomainModelDnsRecordsDkimRecord>>,
}

impl CreateDomainModelDnsRecords {
    pub fn new() -> CreateDomainModelDnsRecords {
        CreateDomainModelDnsRecords {
            dkim_record: None,
            brevo_code: None,
            dmarc_record: None,
        }
    }
}
