/*
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportWebhooksHistory {
    /// Number of days in the past including today (positive integer). _Not compatible with 'startDate' and 'endDate'_
    #[serde(rename = "days", skip_serializing_if = "Option::is_none")]
    pub days: Option<i32>,
    /// Mandatory if endDate is used. Starting date of the history (YYYY-MM-DD). Must be lower than equal to endDate
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    /// Mandatory if startDate is used. Ending date of the report (YYYY-MM-DD). Must be greater than equal to startDate
    #[serde(rename = "endDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    /// Sorting order of records (asc or desc)
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<String>,
    /// Filter the history based on webhook type
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Filter the history for a specific event type
    #[serde(rename = "event")]
    pub event: Event,
    /// Webhook URL to receive CSV file link
    #[serde(rename = "notifyURL")]
    pub notify_url: String,
    /// Filter the history for a specific webhook id
    #[serde(rename = "webhookId", skip_serializing_if = "Option::is_none")]
    pub webhook_id: Option<i32>,
    /// Filter the history for a specific email
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Filter the history for a specific message id. Applicable only for transactional webhooks.
    #[serde(rename = "messageId", skip_serializing_if = "Option::is_none")]
    pub message_id: Option<i32>,
}

impl ExportWebhooksHistory {
    pub fn new(r#type: Type, event: Event, notify_url: String) -> ExportWebhooksHistory {
        ExportWebhooksHistory {
            days: None,
            start_date: None,
            end_date: None,
            sort: None,
            r#type,
            event,
            notify_url,
            webhook_id: None,
            email: None,
            message_id: None,
        }
    }
}
/// Filter the history based on webhook type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "transactional")]
    Transactional,
    #[serde(rename = "marketing")]
    Marketing,
}

impl Default for Type {
    fn default() -> Type {
        Self::Transactional
    }
}
/// Filter the history for a specific event type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "invalid_parameter")]
    InvalidParameter,
    #[serde(rename = "missing_parameter")]
    MissingParameter,
    #[serde(rename = "hardBounce")]
    HardBounce,
    #[serde(rename = "softBounce")]
    SoftBounce,
    #[serde(rename = "delivered")]
    Delivered,
    #[serde(rename = "spam")]
    Spam,
    #[serde(rename = "request")]
    Request,
    #[serde(rename = "opened")]
    Opened,
    #[serde(rename = "click")]
    Click,
    #[serde(rename = "invalid")]
    Invalid,
    #[serde(rename = "deferred")]
    Deferred,
    #[serde(rename = "blocked")]
    Blocked,
    #[serde(rename = "unsubscribed")]
    Unsubscribed,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "uniqueOpened")]
    UniqueOpened,
    #[serde(rename = "loadedByProxy")]
    LoadedByProxy,
    #[serde(rename = "allEvents")]
    AllEvents,
}

impl Default for Event {
    fn default() -> Event {
        Self::InvalidParameter
    }
}
