/*
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWhatsappTemplatesTemplatesInner {
    /// ID of the WhatsApp template
    #[serde(rename = "id")]
    pub id: i64,
    /// Name of the WhatsApp template
    #[serde(rename = "name")]
    pub name: String,
    /// Status of the WhatsApp template
    #[serde(rename = "status")]
    pub status: String,
    /// Language in which template exists
    #[serde(rename = "language")]
    pub language: String,
    /// category of the template
    #[serde(rename = "category")]
    pub category: String,
    /// Error reason in the template creation
    #[serde(rename = "errorReason", skip_serializing_if = "Option::is_none")]
    pub error_reason: Option<String>,
    /// Creation UTC date-time of the WhatsApp template (YYYY-MM-DDTHH:mm:ss.SSSZ)
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// UTC date-time of last modification of the WhatsApp template (YYYY-MM-DDTHH:mm:ss.SSSZ)
    #[serde(rename = "modifiedAt")]
    pub modified_at: String,
}

impl GetWhatsappTemplatesTemplatesInner {
    pub fn new(
        id: i64,
        name: String,
        status: String,
        language: String,
        category: String,
        created_at: String,
        modified_at: String,
    ) -> GetWhatsappTemplatesTemplatesInner {
        GetWhatsappTemplatesTemplatesInner {
            id,
            name,
            status,
            language,
            category,
            error_reason: None,
            created_at,
            modified_at,
        }
    }
}
