/*
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetContactCampaignStats : Campaign Statistics for the contact
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContactCampaignStats {
    #[serde(rename = "messagesSent", skip_serializing_if = "Option::is_none")]
    pub messages_sent: Option<Vec<models::GetExtendedContactDetailsAllOfStatisticsMessagesSent>>,
    #[serde(rename = "hardBounces", skip_serializing_if = "Option::is_none")]
    pub hard_bounces: Option<Vec<models::GetExtendedContactDetailsAllOfStatisticsMessagesSent>>,
    #[serde(rename = "softBounces", skip_serializing_if = "Option::is_none")]
    pub soft_bounces: Option<Vec<models::GetExtendedContactDetailsAllOfStatisticsMessagesSent>>,
    #[serde(rename = "complaints", skip_serializing_if = "Option::is_none")]
    pub complaints: Option<Vec<models::GetExtendedContactDetailsAllOfStatisticsMessagesSent>>,
    #[serde(rename = "unsubscriptions", skip_serializing_if = "Option::is_none")]
    pub unsubscriptions: Option<Box<models::GetContactCampaignStatsUnsubscriptions>>,
    #[serde(rename = "opened", skip_serializing_if = "Option::is_none")]
    pub opened: Option<Vec<models::GetContactCampaignStatsOpenedInner>>,
    #[serde(rename = "clicked", skip_serializing_if = "Option::is_none")]
    pub clicked: Option<Vec<models::GetContactCampaignStatsClickedInner>>,
    #[serde(rename = "transacAttributes", skip_serializing_if = "Option::is_none")]
    pub transac_attributes: Option<Vec<models::GetContactCampaignStatsTransacAttributesInner>>,
    #[serde(rename = "delivered", skip_serializing_if = "Option::is_none")]
    pub delivered: Option<Vec<models::GetExtendedContactDetailsAllOfStatisticsMessagesSent>>,
}

impl GetContactCampaignStats {
    /// Campaign Statistics for the contact
    pub fn new() -> GetContactCampaignStats {
        GetContactCampaignStats {
            messages_sent: None,
            hard_bounces: None,
            soft_bounces: None,
            complaints: None,
            unsubscriptions: None,
            opened: None,
            clicked: None,
            transac_attributes: None,
            delivered: None,
        }
    }
}
