/*
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MainPeriodCreateRewardResponse {
    /// Timestamp when the reward was created
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Unique identifier for the reward
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Id of the loyalty program to which the current reward belongs to
    #[serde(rename = "loyaltyProgramId", skip_serializing_if = "Option::is_none")]
    pub loyalty_program_id: Option<uuid::Uuid>,
    /// Name of the reward
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Public description for the reward
    #[serde(rename = "publicDescription", skip_serializing_if = "Option::is_none")]
    pub public_description: Option<String>,
    /// Public Image for the reward
    #[serde(rename = "publicImage", skip_serializing_if = "Option::is_none")]
    pub public_image: Option<String>,
    /// Public name for the reward
    #[serde(rename = "publicName", skip_serializing_if = "Option::is_none")]
    pub public_name: Option<String>,
    /// Timestamp for when this reward was last updated.
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl MainPeriodCreateRewardResponse {
    pub fn new() -> MainPeriodCreateRewardResponse {
        MainPeriodCreateRewardResponse {
            created_at: None,
            id: None,
            loyalty_program_id: None,
            name: None,
            public_description: None,
            public_image: None,
            public_name: None,
            updated_at: None,
        }
    }
}
