/*
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MainPeriodRuleConditionResponse {
    /// Metric to indicate AND between rules
    #[serde(rename = "and", skip_serializing_if = "Option::is_none")]
    pub and: Option<Vec<models::MainPeriodRuleConditionResponse>>,
    /// Condition of the rule
    #[serde(rename = "lhs", skip_serializing_if = "Option::is_none")]
    pub lhs: Option<Box<models::MainPeriodValueResponse>>,
    /// Selected operator for the rule
    #[serde(rename = "op", skip_serializing_if = "Option::is_none")]
    pub op: Option<String>,
    /// Metric to indicate OR between rules
    #[serde(rename = "or", skip_serializing_if = "Option::is_none")]
    pub or: Option<Vec<models::MainPeriodRuleConditionResponse>>,
    /// Action of the rule
    #[serde(rename = "rhs", skip_serializing_if = "Option::is_none")]
    pub rhs: Option<Box<models::MainPeriodValueResponse>>,
}

impl MainPeriodRuleConditionResponse {
    pub fn new() -> MainPeriodRuleConditionResponse {
        MainPeriodRuleConditionResponse {
            and: None,
            lhs: None,
            op: None,
            or: None,
            rhs: None,
        }
    }
}
