/*
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderProductsInner : Details for the Products in an order.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderProductsInner {
    /// ID of the product.
    #[serde(rename = "productId")]
    pub product_id: String,
    /// How many pieces of the product the visitor has added to the cart.
    #[serde(rename = "quantity")]
    pub quantity: f64,
    /// Product ID of the red color shirts.
    #[serde(rename = "variantId", skip_serializing_if = "Option::is_none")]
    pub variant_id: Option<String>,
    /// The price of a unit of product
    #[serde(rename = "price")]
    pub price: f64,
}

impl OrderProductsInner {
    /// Details for the Products in an order.
    pub fn new(product_id: String, quantity: f64, price: f64) -> OrderProductsInner {
        OrderProductsInner {
            product_id,
            quantity,
            variant_id: None,
            price,
        }
    }
}
