/*
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubAccountDetailsResponsePlanInfoFeatures : Features available on the sub-account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubAccountDetailsResponsePlanInfoFeatures {
    #[serde(rename = "inbox", skip_serializing_if = "Option::is_none")]
    pub inbox: Option<Box<models::SubAccountDetailsResponsePlanInfoFeaturesInbox>>,
    #[serde(rename = "landingPage", skip_serializing_if = "Option::is_none")]
    pub landing_page: Option<Box<models::SubAccountDetailsResponsePlanInfoFeaturesLandingPage>>,
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Box<models::SubAccountDetailsResponsePlanInfoFeaturesUsers>>,
    #[serde(rename = "salesUsers", skip_serializing_if = "Option::is_none")]
    pub sales_users: Option<Box<models::SubAccountDetailsResponsePlanInfoFeaturesSalesUsers>>,
}

impl SubAccountDetailsResponsePlanInfoFeatures {
    /// Features available on the sub-account
    pub fn new() -> SubAccountDetailsResponsePlanInfoFeatures {
        SubAccountDetailsResponsePlanInfoFeatures {
            inbox: None,
            landing_page: None,
            users: None,
            sales_users: None,
        }
    }
}
