/*
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TemplatePreviewModel {
    /// Sender email address
    #[serde(rename = "fromEmail", skip_serializing_if = "Option::is_none")]
    pub from_email: Option<String>,
    /// Sender Name
    #[serde(rename = "fromName", skip_serializing_if = "Option::is_none")]
    pub from_name: Option<String>,
    /// Html content of the template
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    /// subject of the template
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[serde(rename = "usedFeedNames", skip_serializing_if = "Option::is_none")]
    pub used_feed_names: Option<Vec<String>>,
    /// Preview text of the template
    #[serde(rename = "previewText", skip_serializing_if = "Option::is_none")]
    pub preview_text: Option<String>,
}

impl TemplatePreviewModel {
    pub fn new() -> TemplatePreviewModel {
        TemplatePreviewModel {
            from_email: None,
            from_name: None,
            html: None,
            subject: None,
            used_feed_names: None,
            preview_text: None,
        }
    }
}
